name:                line-bot-kiirotori
version:             0.1.0.0
github:              "falgon/line-bot-kiirotori"
license:             BSD3
author:              "Roki"
maintainer:          "falgon53@yahoo.co.jp"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/falgon/line-bot-kiirotori#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- transformers
- unordered-containers
- time
- safe-exceptions
- http-conduit
- jose
- bytestring
- utf8-string
- lens
- mtl
- hedis
- extra
- monad-parallel
- scientific
- servant
- servant-server
- warp
- warp-tls
- monad-logger
- base64-bytestring
- vector
- cryptohash-sha256
- http-media
- path
- path-io
- htoml
- optparse-applicative
- megaparsec
- fixed-vector
- mysql-haskell
- io-streams

flags:
  release:
    manual: true
    default: false

library:
  source-dirs: src
  when:
      condition: (flag(release))
      cpp-options: -DRELEASE

executables:
  line-bot-kiirotori:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - line-bot-kiirotori

tests:
  line-bot-kiirotori-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - line-bot-kiirotori
