name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup GHC
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
          enable-stack: true
          stack-version: '2.9.3'
      - name: Cache
        uses: actions/cache@v2
        id: stack-cache
        with:
          path: ~/.stack
          key: stack-v1-${{ runner.os }}-${{ hashFiles('stack.yaml') }}
      - name: Setup haskell stack
        if: steps.stack-cache.outputs.cache-hit != 'true'
        run: |
           stack config set system-ghc --global true
           stack config set install-ghc --global false
      - name: Build
        run: stack build --fast
      - name: Test
        run: stack test
